<?php

namespace AppBundle\Repository;

/**
 * BlogPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 */
class BlogPostRepository extends \Doctrine\ORM\EntityRepository
{

    public function createFindOneByIdQuery(int $id)
    {
        $query = $this->_em->createQuery(
            "
                SELECT bp
                FROM AppBundle:BlogPost bp
                WHERE bp.id = :id
            "
        );

        $query->setParameter('id', $id);

        return $query;
    }

    public function createFindAllQuery()
    {
        $query = $this->_em->createQuery(
            "
                SELECT bp
                FROM AppBundle:BlogPost bp
            "
        );

        return $query;
    }


}
