app:
    resource: '@AppBundle/Controller/'
    type: annotation

list:
    path: /list
    defaults: {_controller: AppBundle:BlogPost:list}

create:
    path: /create
    defaults: {_controller: AppBundle:BlogPost:create}

edit:
    path: /edit/{blogPost}
    defaults: {_controller: AppBundle:BlogPost:edit}

delete:
    path: /delete/{blogPost}
    defaults: {_controller: AppBundle:BlogPost:delete}


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: "/doc"

get:
    path: /get/{id}
    defaults: {_controller: AppBundle:BlogPost:get}

api:
    type: rest
    resource: "routing_api.yml"
