app:
    resource: '@AppBundle/Controller/'
    type: annotation

list:
    path: /list
    defaults: {_controller: AppBundle:BlogPost:list}

create:
    path: /create
    defaults: {_controller: AppBundle:BlogPost:create}